### ISSUE TITLE
CI doesn't detect gradle syntax errors

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-scala-seed.g8#85] opened 2019-01-08 13:23 UTC
As reported in #74, #81, #72, ... some of the g8 template files use `$` and `templatecontrol` messe them up breaking the `g8` templating syntax.

The CI build in this repo doesn't detect this issue.

Related: https://github.com/foundweekends/giter8/pull/408 and https://github.com/foundweekends/giter8/issues/334

**Comment by TimMoore** [comment] 2019-01-09 23:40
There is a gradle test, but it is configured as an allowed failure:
https://travis-ci.org/playframework/play-scala-seed.g8/builds/475599011

Looks like it was introduced here:
https://github.com/playframework/play-scala-seed.g8/commit/b28045aece55f3993a0f9e2b78aece7ca61804c9#diff-354f30a63fb0907d4ad57269548329e3R24

> ```
>     # Current release of Gradle still does not supports Play 2.7.x releases
>     # As soon as there is a release of Gradle that fixes that, we can then
>     # remove this allowed failure.
> ```

@marcospereira it sounds like it should be safe to configure the 2.6.x branch to require this to pass, correct?

Looks like the underlying problem was fixed here: https://github.com/lightbend/templatecontrol/pull/85

**Comment by TimMoore** [comment] 2019-01-09 23:45
Actually, this problem affects any use of `sbt new`, not just for Gradle users.

The problem is detected in the normal build, too, but does not cause the build to fail:
https://travis-ci.org/playframework/play-scala-seed.g8/jobs/475599012#L678

```
Falling back to file copy for /home/travis/build/playframework/play-scala-seed.g8/src/main/g8/build.gradle: File: /home/travis/build/playframework/play-scala-seed.g8/src/main/g8/build.gradle, 59:71: mismatched input '.' expecting LPAREN
```

The message is slightly different from what's reported by users, and looks like it's just a warning with fallback behavior. Maybe it depends on the sbt version used?

**Comment by TimMoore** [comment] 2019-01-09 23:46
Related discussion: https://github.com/akka/akka-http-quickstart-scala.g8/issues/15

**Comment by mkurz** [comment] 2023-03-02 20:31
Gradle support has been dropped from this repo #119 therefore closing this issue.
However, [meanwhile gradle does actually support Play 2.8](https://gradle.github.io/playframework/#change_log), so if someone wants to it back here feel free to add a PR.

**Closed as completed by mkurz** 2023-03-02 20:31 UTC
Labels: status:backlog
