### ISSUE TITLE
sbt compile for play 3.0.1 and sbt 1.9.8 have dependency issues

### ISSUE THREAD

**Issue by minnieshi** [playframework/play-scala-seed.g8#229] opened 2024-02-04 18:33 UTC
### Problems overview
I am trying the play 3.0.1 with scala 2.13.12 with some simple post/put/get stuff without issues.
once I've added 3 more dependices, it starts to have compatiblility issues. 

Can anyone please guide me the quick solution?

### environment/versions

- the sbt version
```
sbt.version=1.9.8
```

- the scala and the 3 dependencies (jwt-play, jwt-core, jwks-rsa)

```
scalaVersion := "2.13.12"

libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "7.0.0" % Test
// to secure with auth0,jwks-rsa: download and retrieve the public key for us;
// and jwt-scala: which will take this public key and decode the token for us, as well as perform some basic validation

libraryDependencies ++= Seq(
  "com.github.jwt-scala" %% "jwt-play" % "9.1.1",
  "com.github.jwt-scala" %% "jwt-core" % "9.1.1",
  "com.auth0"             % "jwks-rsa" % "0.22.1"
)
```

- the sbt and play versions (plugins.sbt file):

```
addSbtPlugin("org.playframework"        % "sbt-plugin"          % "3.0.1")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.16.2")
//ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml"           % VersionScheme.Always
```

### sbt clean compile output

> [info] Play is run entirely by the community. Please consider contributing and/or donating:
[info] https://www.playframework.com/sponsors
[info]
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed 4 Feb 2024, 19.21.03
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.13:2.2.0 (early-semver) is selected over 1.2.0
[error] 	    +- org.playframework.twirl:twirl-api_2.13:2.0.3       (depends on 2.2.0)
[error] 	    +- com.typesafe.play:twirl-api_2.13:1.5.1             (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:90)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.13:2.2.0 (early-semver) is selected over 1.2.0
[error] 	    +- org.playframework.twirl:twirl-api_2.13:2.0.3       (depends on 2.2.0)
[error] 	    +- com.typesafe.play:twirl-api_2.13:1.5.1             (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] Total time: 1 s, completed 4 Feb 2024, 19.21.04

### What I've tried
I've tried one of the work around (see my above plugins.sbt commented out line) suggested here: https://github.com/playframework/playframework/issues/11522
but it did not help

**Comment by gmethvin** [comment] 2024-02-05 01:13
It looks like you're using a third-party library that isn't compatible with Play 3.0: https://mvnrepository.com/artifact/com.github.jwt-scala/jwt-play_2.13/9.1.1. It appears version 10.x is compatible with Play 3. Closing since this is not a bug.

**Closed as not planned** 2024-02-05 01:14 UTC

**Comment by minnieshi** [comment] 2024-02-05 19:08
I confirm no more issues after I updated the version to be 10.....

In the future maybe I should raise this kind of thing in Q&A or discussion
